site_name: Michael Tinsley
site_url: "https://michaeltinsley.github.io"
site_description: "A personal Weblog about MLOps, ML, and assorted technologies"
repo_url: https://github.com/michaeltinsley/michaeltinsley.github.io
repo_name: michaeltinsley/michaeltinsley.github.io
edit_uri: edit/source/docs/
copyright: "&copy; 2025, Michael Tinsley"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michaeltinsley
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/michaeltinsley
      name: LinkedIn
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Blog:
      - posts/index.md

theme:
  name: material
  icon:
    repo: material/github
    logo: material/hand-wave
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: michaeltinsley
      repo: michaeltinsley.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - privacy:
      assets_fetch: true
      assets_fetch_dir: assets/external
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: full
      post_url_date_format: yyyy
      post_url_format: "posts/{file}"
      post_excerpt_max_authors: 2
      post_excerpt_max_categories: 3
      post_readtime: true
      post_readtime_words_per_minute: 200
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "~2~"
      pagination_if_single_page: false
      pagination_keep_content: true
      authors_file: "{blog}/.authors.yml"
      categories_allowed:
        - Software Development
        - Technology
        - Personal
        - Projects
        - Learning
        - Machine Learning
        - MLOps
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: michaeltinsley/michaeltinsley.github.io
      branch: main
