site_name: Michael Tinsley
site_url: "https://michaeltinsley.github.io"
site_description: "A personal Weblog about MLOps, ML, and assorted technologies"
repo_url: https://github.com/michaeltinsley/michaeltinsley.github.io
repo_name: michaeltinsley/michaeltinsley.github.io
edit_uri: edit/source/docs/
copyright: "&copy; 2025, Michael Tinsley"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michaeltinsley
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/michaeltinsley
      name: LinkedIn
  generator: false

theme:
  name: material
  icon:
    repo: material/github
    logo: material/cube
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.share
    - toc.follow
    - toc.integrate
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - blog:
      blog_dir: .
      categories_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 200
      pagination_per_page: 10
      categories_allowed:
        - MLOps
        - Infrastructure
        - ML Engineering
        - Projects
        - Learning
        - Tools
