authors:
  michaeltinsley:
    name: Michael Tinsley
    description: MLOps Engineer
    avatar: https://github.com/michaeltinsley.png
    slug: michaeltinsley
    url: https://github.com/michaeltinsley
